name: Create Security Fix Pull Request
on: [push]
jobs:
  patch:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/checkout@master
      - run: npm install -g npm
      - rum: npm -v
      - run: npm audit fix
