name: Create Security Fix Pull Request
on: [push]
jobs:
  patch:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
