name: Create Security Fix Pull Request
jobs:
  patch:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/checkout@master
      - run: npm install -g npm
      - rum: npm -v
      - run: npm audit fix
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2.1.0
        with:
          title: Security Update into master.
          labels: Auto PR
          branch: securityFix
          token: ${{ secrets.GITHUB }}

name: Create Security Fix Pull Request
on: [push]
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'

